cellsociety_team19: Shark Class Reference
Shark Class Reference
Public Member Functions
Shark (Cell cell, Paint color, int startEnergy)
void spendEnergy ()
boolean checkEnergy ()
void eat (int fishEnergy)
Shark breed (Cell cell)
Public Member Functions inherited from Fish
Fish (Cell cell, Paint color)
boolean canBreed (int time)
Fish breed (Cell cell)
void surviveTurn ()
void reset ()
Public Member Functions inherited from Mover
Mover (Cell cell, Paint color)
Cell getCell ()
boolean isState (Paint paint)
Paint getState ()
void move (Cell end)
Private Attributes
int energyLeft
Detailed Description
Definition at line 4 of file Shark.java.
Constructor & Destructor Documentation
Shark.Shark (Cell cell, Paint color, int startEnergy)
Definition at line 7 of file Shark.java.
Referenced by breed().
Member Function Documentation
Shark Shark.breed (Cell cell)
Definition at line 24 of file Shark.java.
References Mover.getState(), Fish.reset(), and Shark().
boolean Shark.checkEnergy ()
Definition at line 16 of file Shark.java.
Referenced by Wator.ruleTwo().
void Shark.eat (int fishEnergy)
Definition at line 20 of file Shark.java.
Referenced by Wator.ruleTwo().
void Shark.spendEnergy ()
Definition at line 12 of file Shark.java.
Referenced by Wator.ruleTwo().
Member Data Documentation
int Shark.energyLeft private
Definition at line 5 of file Shark.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/Shark.java