cellsociety_team19: Cell Class Reference
Cell Class Reference
Public Member Functions
Cell (int posX, int posY)
void setState (Paint paint)
void update ()
void setNextState (Paint paint)
boolean isState (Paint paint)
int getPosX ()
int getPosY ()
Paint getState ()
Private Attributes
Paint nextColor
Paint currentColor
int x
int y
Detailed Description
Definition at line 5 of file Cell.java.
Constructor & Destructor Documentation
Cell.Cell (int posX, int posY)
Definition at line 11 of file Cell.java.
Member Function Documentation
int Cell.getPosX ()
Definition at line 39 of file Cell.java.
References x.
Referenced by Grid.getNeighbors().
int Cell.getPosY ()
Definition at line 43 of file Cell.java.
References y.
Referenced by Grid.getNeighbors().
Paint Cell.getState ()
Definition at line 47 of file Cell.java.
References currentColor.
Referenced by Segregation.getSamePercent(), and Wator.ruleOne().
boolean Cell.isState (Paint paint)
Definition at line 35 of file Cell.java.
Referenced by GameOfLife.ruleOne(), Fire.ruleOne(), GameOfLife.ruleTwo(), and Fire.ruleTwo().
void Cell.setNextState (Paint paint)
Definition at line 31 of file Cell.java.
Referenced by Mover.Mover(), GameOfLife.ruleOne(), Fire.ruleOne(), GameOfLife.ruleTwo(), Fire.ruleTwo(), setState(), and Fire.setUpInitialConfig().
void Cell.setState (Paint paint)
Definition at line 16 of file Cell.java.
References setNextState(), and update().
Referenced by MoveCellularAutomata.move(), and Wator.ruleTwo().
void Cell.update ()
Definition at line 21 of file Cell.java.
References nextColor.
Referenced by Mover.Mover(), and setState().
Member Data Documentation
Paint Cell.currentColor private
Definition at line 7 of file Cell.java.
Referenced by getState().
Paint Cell.nextColor private
Definition at line 6 of file Cell.java.
Referenced by update().
int Cell.x private
Definition at line 8 of file Cell.java.
Referenced by getPosX().
int Cell.y private
Definition at line 9 of file Cell.java.
Referenced by getPosY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/Cell.java