cellsociety_team19: State Class Reference
State Class Reference
Public Member Functions
State (String name, Color color)
void update ()
void addToUpdate (Cell cell)
boolean contains (Cell cell)
ArrayList< Cell > getMyCurrent ()
void setMyCurrent (ArrayList< Cell > myCurrent)
Private Attributes
String myName
ArrayList< Cell > myCurrent
ArrayList< Cell > myNext
Color myColor
Detailed Description
Definition at line 6 of file State.java.
Constructor & Destructor Documentation
State.State (String name, Color color)
Definition at line 12 of file State.java.
References setMyCurrent().
Member Function Documentation
void State.addToUpdate (Cell cell)
Definition at line 27 of file State.java.
Referenced by Segregation.ruleOne(), Fire.ruleOne(), GameOfLife.ruleOne(), Fire.ruleTwo(), GameOfLife.ruleTwo(), Fire.setUpInitialConfig(), and GameOfLife.setUpInitialConfig().
boolean State.contains (Cell cell)
Definition at line 31 of file State.java.
References getMyCurrent().
ArrayList<Cell> State.getMyCurrent ()
Definition at line 35 of file State.java.
References myCurrent.
Referenced by contains(), Segregation.ruleOne(), and update().
void State.setMyCurrent (ArrayList< Cell > myCurrent)
Definition at line 39 of file State.java.
References myCurrent.
Referenced by State(), and update().
void State.update ()
Definition at line 19 of file State.java.
References getMyCurrent(), and setMyCurrent().
Member Data Documentation
Color State.myColor private
Definition at line 10 of file State.java.
ArrayList<Cell> State.myCurrent private
Definition at line 8 of file State.java.
Referenced by getMyCurrent(), and setMyCurrent().
String State.myName private
Definition at line 7 of file State.java.
ArrayList<Cell> State.myNext private
Definition at line 9 of file State.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/State.java