cellsociety_team19: CellularAutomata Class Reference
CellularAutomata Class Reference abstract
Public Member Functions
CellularAutomata (String name)
void init (Grid grid, Map< String, Integer > parameters, String[] colors)
CellularAutomata init (Grid grid, Map< String, Integer > parameters, String[] colors, double[] probs)
CellularAutomata init (Grid grid, Map< String, Integer > parameters, String[] colors, int[][][] points)
void setUpInitialConfig (String[] colors, double[] probs)
void setUpInitialConfig (String[] colors, int[][][] points)
void rule (Cell cell, Predicate< Cell > tester, Consumer< Cell > change)
void updateNextGen ()
void checkRules (Cell cell)
void checkRules ()
void handleUpdate ()
double getRandomDouble ()
Grid getGrid ()
String getName ()
double getProb ()
Private Attributes
String myName
double myProb
Grid myGrid
Random myRandom
Detailed Description
Abstract class for all simulations to be run
Definition at line 16 of file CellularAutomata.java.
Constructor & Destructor Documentation
CellularAutomata.CellularAutomata (String name)
Definition at line 22 of file CellularAutomata.java.
Member Function Documentation
void CellularAutomata.checkRules (Cell cell)
Definition at line 78 of file CellularAutomata.java.
void CellularAutomata.checkRules ()
Definition at line 82 of file CellularAutomata.java.
References getGrid().
Referenced by updateNextGen().
Grid CellularAutomata.getGrid ()
Definition at line 102 of file CellularAutomata.java.
References myGrid.
Referenced by Fire.checkNextToFire(), GameOfLife.checkRules(), checkRules(), Segregation.getSamePercent(), handleUpdate(), CellSocietyView.makeCAGame(), Wator.ruleOne(), GameOfLife.ruleOne(), GameOfLife.ruleTwo(), Wator.ruleTwo(), Fire.setUpInitialConfig(), Segregation.setUpInitialConfig(), setUpInitialConfig(), and Wator.setUpInitialConfig().
String CellularAutomata.getName ()
Definition at line 106 of file CellularAutomata.java.
References myName.
Referenced by XMLReader.addGameType(), and Main.start().
double CellularAutomata.getProb ()
Definition at line 110 of file CellularAutomata.java.
References myProb.
Referenced by Fire.checkRules(), Segregation.ruleOne(), and Fire.ruleTwo().
double CellularAutomata.getRandomDouble ()
Definition at line 98 of file CellularAutomata.java.
Referenced by Fire.checkRules(), Fire.ruleTwo(), Fire.setUpInitialConfig(), Segregation.setUpInitialConfig(), setUpInitialConfig(), and Wator.setUpInitialConfig().
void CellularAutomata.handleUpdate ()
Definition at line 90 of file CellularAutomata.java.
References getGrid().
Referenced by updateNextGen().
void CellularAutomata.init (Grid grid, Map< String, Integer > parameters, String[] colors)
Definition at line 27 of file CellularAutomata.java.
Referenced by init().
CellularAutomata CellularAutomata.init (Grid grid, Map< String, Integer > parameters, String[] colors, double[] probs)
Definition at line 32 of file CellularAutomata.java.
References init(), and setUpInitialConfig().
CellularAutomata CellularAutomata.init (Grid grid, Map< String, Integer > parameters, String[] colors, int points[][][])
Definition at line 38 of file CellularAutomata.java.
References init(), and setUpInitialConfig().
void CellularAutomata.rule (Cell cell, Predicate< Cell > tester, Consumer< Cell > change)
Definition at line 67 of file CellularAutomata.java.
Referenced by GameOfLife.checkRules(), and Fire.checkRules().
void CellularAutomata.setUpInitialConfig (String[] colors, double[] probs)
Definition at line 44 of file CellularAutomata.java.
References getGrid(), and getRandomDouble().
Referenced by init().
void CellularAutomata.setUpInitialConfig (String[] colors, int points[][][])
Definition at line 59 of file CellularAutomata.java.
References Grid.getCellAt(), getGrid(), and Cell.setState().
void CellularAutomata.updateNextGen ()
Definition at line 73 of file CellularAutomata.java.
References checkRules(), and handleUpdate().
Referenced by CellSocietyView.updateView().
Member Data Documentation
Grid CellularAutomata.myGrid private
Definition at line 19 of file CellularAutomata.java.
Referenced by getGrid().
String CellularAutomata.myName private
Definition at line 17 of file CellularAutomata.java.
Referenced by getName().
double CellularAutomata.myProb private
Definition at line 18 of file CellularAutomata.java.
Referenced by getProb().
Random CellularAutomata.myRandom private
Definition at line 20 of file CellularAutomata.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/CellularAutomata.java