cellsociety_team19: Fire Class Reference
Fire Class Reference
Public Member Functions
Fire ()
Scene init (int size, int width, int height)
void setUpInitialConfig ()
void applyRules ()
void ruleOne (Cell cell)
void ruleTwo (Cell cell)
void handleUpdate ()
Public Member Functions inherited from CellularAutomata
CellularAutomata (String name, int[][] neighborhood, double prob)
abstract Scene init (int size, int width, int height)
void addState (String name, Color color)
State findState (String name)
Timeline makeTimeline (int time)
void update ()
abstract void applyRules ()
abstract void handleUpdate ()
Button pause ()
Button play ()
Button stepForward ()
Button fastForward ()
Button slowDown ()
Grid getGrid ()
void setGrid (Grid myGrid)
Map< String, State > getMyStates ()
void setMyStates (Map< String, State > myStates)
Group getMyRoot ()
void setMyRoot (Group myRoot)
String getName ()
void setName (String name)
int[][] getMyNeighborhood ()
void setMyNeighborhood (int[][] myNeighborhood)
double getMyProb ()
void setMyProb (double myProb)
Detailed Description
Definition at line 12 of file Fire.java.
Constructor & Destructor Documentation
Fire.Fire ()
Definition at line 14 of file Fire.java.
Member Function Documentation
void Fire.applyRules ()
Definition at line 57 of file Fire.java.
References CellularAutomata.getGrid(), ruleOne(), and ruleTwo().
void Fire.handleUpdate ()
Definition at line 96 of file Fire.java.
References CellularAutomata.getMyStates().
Referenced by setUpInitialConfig().
Scene Fire.init (int size, int width, int height)
Definition at line 19 of file Fire.java.
References CellularAutomata.addState(), CellularAutomata.fastForward(), CellularAutomata.getMyNeighborhood(), CellularAutomata.getMyRoot(), CellularAutomata.pause(), CellularAutomata.play(), CellularAutomata.setGrid(), CellularAutomata.setMyRoot(), CellularAutomata.setMyStates(), CellularAutomata.setName(), setUpInitialConfig(), CellularAutomata.slowDown(), and CellularAutomata.stepForward().
void Fire.ruleOne (Cell cell)
Definition at line 67 of file Fire.java.
References State.addToUpdate(), and CellularAutomata.findState().
Referenced by applyRules().
void Fire.ruleTwo (Cell cell)
Definition at line 74 of file Fire.java.
References State.addToUpdate(), CellularAutomata.findState(), CellularAutomata.getGrid(), CellularAutomata.getMyProb(), and Grid.getNeighbors().
Referenced by applyRules().
void Fire.setUpInitialConfig ()
Definition at line 39 of file Fire.java.
References State.addToUpdate(), CellularAutomata.findState(), Grid.getCellAt(), Grid.getCells(), CellularAutomata.getGrid(), and handleUpdate().
Referenced by init().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/Fire.java