cellsociety_team19: GameOfLife Class Reference
GameOfLife Class Reference
Public Member Functions
GameOfLife ()
Scene init (int size, int width, int height)
void setUpInitialConfig (int size)
void applyRules ()
void ruleOne (Cell cell)
void ruleTwo (Cell cell)
void handleUpdate ()
Public Member Functions inherited from CellularAutomata
CellularAutomata (String name, int[][] neighborhood, double prob)
abstract Scene init (int size, int width, int height)
void addState (String name, Color color)
State findState (String name)
Timeline makeTimeline (int time)
void update ()
abstract void applyRules ()
abstract void handleUpdate ()
Button pause ()
Button play ()
Button stepForward ()
Button fastForward ()
Button slowDown ()
Grid getGrid ()
void setGrid (Grid myGrid)
Map< String, State > getMyStates ()
void setMyStates (Map< String, State > myStates)
Group getMyRoot ()
void setMyRoot (Group myRoot)
String getName ()
void setName (String name)
int[][] getMyNeighborhood ()
void setMyNeighborhood (int[][] myNeighborhood)
double getMyProb ()
void setMyProb (double myProb)
Detailed Description
Definition at line 20 of file GameOfLife.java.
Constructor & Destructor Documentation
GameOfLife.GameOfLife ()
Definition at line 23 of file GameOfLife.java.
Member Function Documentation
void GameOfLife.applyRules ()
Definition at line 62 of file GameOfLife.java.
References CellularAutomata.getMyStates(), ruleOne(), and ruleTwo().
void GameOfLife.handleUpdate ()
Definition at line 109 of file GameOfLife.java.
References CellularAutomata.getMyStates().
Referenced by setUpInitialConfig().
Scene GameOfLife.init (int size, int width, int height)
Definition at line 27 of file GameOfLife.java.
References CellularAutomata.addState(), CellularAutomata.fastForward(), CellularAutomata.getMyNeighborhood(), CellularAutomata.getMyRoot(), CellularAutomata.pause(), CellularAutomata.play(), CellularAutomata.setGrid(), CellularAutomata.setMyRoot(), CellularAutomata.setMyStates(), CellularAutomata.setName(), setUpInitialConfig(), CellularAutomata.slowDown(), and CellularAutomata.stepForward().
void GameOfLife.ruleOne (Cell cell)
Definition at line 71 of file GameOfLife.java.
References State.addToUpdate(), CellularAutomata.findState(), CellularAutomata.getGrid(), and Grid.getNeighbors().
Referenced by applyRules().
void GameOfLife.ruleTwo (Cell cell)
Definition at line 90 of file GameOfLife.java.
References State.addToUpdate(), CellularAutomata.findState(), CellularAutomata.getGrid(), and Grid.getNeighbors().
Referenced by applyRules().
void GameOfLife.setUpInitialConfig (int size)
Definition at line 47 of file GameOfLife.java.
References State.addToUpdate(), CellularAutomata.findState(), CellularAutomata.getGrid(), and handleUpdate().
Referenced by init().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/GameOfLife.java