cellsociety_team19: Fish Class Reference
Fish Class Reference
Public Member Functions
Fish (Cell cell, Paint color, int spawn, int energy)
boolean canBreed ()
Fish breed (Cell cell)
void surviveTurn ()
boolean checkEnergy ()
void eat ()
Public Member Functions inherited from Mover
Mover (Cell cell, Paint color)
Cell getCell ()
boolean isState (Paint paint)
Paint getState ()
void move (Cell end)
Private Attributes
int spawnTime
int energyLeft
Static Private Attributes
static final int START_ENERGY = 5
static final int FISH_ENERGY =5
static final int BREED_TIME = 5
Detailed Description
Keeps track of fish stats
Definition at line 7 of file Fish.java.
Constructor & Destructor Documentation
Fish.Fish (Cell cell, Paint color, int spawn, int energy)
Definition at line 15 of file Fish.java.
Referenced by breed().
Member Function Documentation
Fish Fish.breed (Cell cell)
Definition at line 25 of file Fish.java.
References Fish(), and Mover.getState().
Referenced by Wator.breedIfCan().
boolean Fish.canBreed ()
Definition at line 21 of file Fish.java.
Referenced by Wator.breedIfCan().
boolean Fish.checkEnergy ()
Definition at line 35 of file Fish.java.
Referenced by Wator.ruleTwo().
void Fish.eat ()
Definition at line 39 of file Fish.java.
References FISH_ENERGY.
Referenced by Wator.ruleTwo().
void Fish.surviveTurn ()
Definition at line 30 of file Fish.java.
Referenced by Wator.ruleOne(), and Wator.ruleTwo().
Member Data Documentation
final int Fish.BREED_TIME = 5 static private
Definition at line 10 of file Fish.java.
int Fish.energyLeft private
Definition at line 13 of file Fish.java.
final int Fish.FISH_ENERGY =5 static private
Definition at line 9 of file Fish.java.
Referenced by eat().
int Fish.spawnTime private
Definition at line 12 of file Fish.java.
final int Fish.START_ENERGY = 5 static private
Definition at line 8 of file Fish.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/Fish.java