cellsociety_team19: MoveCellularAutomata Class Reference
MoveCellularAutomata Class Reference abstract
Public Member Functions
MoveCellularAutomata (String name, int size, int[][] neighborhood, double prob)
void setEmptyColor (Paint paint)
ArrayList< Mover > getMovers ()
void addToRemove (Mover mover)
void move (Mover mover, Cell to)
void addMover (Mover mover)
void addNewMover (Mover mover)
abstract void checkRules (Mover mover)
void checkRules ()
void updateNextGen ()
Cell getRandomCell (ArrayList< Cell > list)
Public Member Functions inherited from CellularAutomata
CellularAutomata (String name, int size, int[][] neighborhood, double prob)
abstract void setUpInitialConfig ()
void updateNextGen ()
abstract void checkRules ()
void handleUpdate ()
double getRandomDouble ()
Grid getGrid ()
String getName ()
int[][] getMyNeighborhood ()
double getMyProb ()
Private Attributes
ArrayList< Mover > alreadyMoved
ArrayList< Mover > allMovers
ArrayList< Mover > toBeRemoved
ArrayList< Mover > toBeAdded
Paint empty
Detailed Description
Definition at line 7 of file MoveCellularAutomata.java.
Constructor & Destructor Documentation
MoveCellularAutomata.MoveCellularAutomata (String name, int size, int neighborhood[][], double prob)
Definition at line 15 of file MoveCellularAutomata.java.
Member Function Documentation
void MoveCellularAutomata.addMover (Mover mover)
Definition at line 40 of file MoveCellularAutomata.java.
Referenced by Segregation.setUpInitialConfig(), and Wator.setUpInitialConfig().
void MoveCellularAutomata.addNewMover (Mover mover)
Definition at line 44 of file MoveCellularAutomata.java.
Referenced by Wator.breed().
void MoveCellularAutomata.addToRemove (Mover mover)
Definition at line 30 of file MoveCellularAutomata.java.
Referenced by Wator.ruleOne(), and Wator.ruleTwo().
abstract void MoveCellularAutomata.checkRules (Mover mover) abstract
void MoveCellularAutomata.checkRules ()
Definition at line 50 of file MoveCellularAutomata.java.
Referenced by updateNextGen().
ArrayList<Mover> MoveCellularAutomata.getMovers ()
Definition at line 26 of file MoveCellularAutomata.java.
References allMovers.
Cell MoveCellularAutomata.getRandomCell (ArrayList< Cell > list)
Definition at line 68 of file MoveCellularAutomata.java.
Referenced by Wator.ruleOne(), Segregation.ruleOne(), and Wator.ruleTwo().
void MoveCellularAutomata.move (Mover mover, Cell to)
Definition at line 34 of file MoveCellularAutomata.java.
References Mover.getCell(), Mover.getState(), Mover.move(), and Cell.setState().
Referenced by Wator.ruleOne(), and Wator.ruleTwo().
void MoveCellularAutomata.setEmptyColor (Paint paint)
Definition at line 22 of file MoveCellularAutomata.java.
Referenced by Segregation.Segregation(), and Wator.Wator().
void MoveCellularAutomata.updateNextGen ()
Definition at line 57 of file MoveCellularAutomata.java.
References checkRules().
Member Data Documentation
ArrayList<Mover> MoveCellularAutomata.allMovers private
Definition at line 10 of file MoveCellularAutomata.java.
Referenced by getMovers().
ArrayList<Mover> MoveCellularAutomata.alreadyMoved private
Definition at line 9 of file MoveCellularAutomata.java.
Paint MoveCellularAutomata.empty private
Definition at line 13 of file MoveCellularAutomata.java.
ArrayList<Mover> MoveCellularAutomata.toBeAdded private
Definition at line 12 of file MoveCellularAutomata.java.
ArrayList<Mover> MoveCellularAutomata.toBeRemoved private
Definition at line 11 of file MoveCellularAutomata.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/MoveCellularAutomata.java