cellsociety_team19: CellSocietyView Class Reference
CellSocietyView Class Reference
Public Member Functions
CellSocietyView (int width, int height, String shape)
Scene getScene ()
Private Member Functions
void setUp ()
void setUpGameTypes ()
void addGameType (CellularAutomata ca)
void setUpGridTypes ()
void setUpNbhoodTypes ()
void loadNewFile ()
void parseFile (File file)
void makeCAGame (String gameName, int cellNum, String neighborhood, double prob, String gridType)
void updateView ()
void makeTimeline (int time)
Button makeLoadButton ()
VBox makeButtons ()
Button makeStepButton ()
Button makeSlowButton ()
Button makeFFButton ()
Button makePauseButton ()
Button makePlayButton ()
Button makeUIButton (String name, EventHandler< MouseEvent > e)
Private Attributes
CellularAutomata myCA
GridDrawer myGridView
Timeline myAnimation
Scene myScene
int myWidth
int myHeight
ResourceBundle myButtonNames
BorderPane myRoot
HashMap< String, CellularAutomata > gameTypes
HashMap< String, Grid > gridTypes
HashMap< String, int[][]> nbhoodTypes
Static Private Attributes
static final double ACCELERATE_RATE = 1.25
static final double SLOW_RATE = .8
static final int[][] NEAR_NEIGHBORHOOD = new int[][] {{-1, 0}, {1, 0}, {0, 1}, {0, -1}}
static final int[][] MOORE_NEIGHBORHOOD = new int[][] {{-1, 0}, {1, 0}, {0, 1}, {0, -1}, {-1, -1}, {-1, 1}, {1, -1}, {1, 1}}
static final String DEFAULT_RESOURCE_PACKAGE = "resources/"
static final int FRAME_RATE = 2000
Detailed Description
Displays the grid and contained cells for each simulation
Definition at line 24 of file CellSocietyView.java.
Constructor & Destructor Documentation
CellSocietyView.CellSocietyView (int width, int height, String shape)
Definition at line 46 of file CellSocietyView.java.
References makeLoadButton(), and setUp().
Member Function Documentation
void CellSocietyView.addGameType (CellularAutomata ca) private
Definition at line 72 of file CellSocietyView.java.
References CellularAutomata.getName().
Referenced by setUpGameTypes().
Scene CellSocietyView.getScene ()
Definition at line 90 of file CellSocietyView.java.
References myScene.
Referenced by Main.start().
void CellSocietyView.loadNewFile () private
Definition at line 94 of file CellSocietyView.java.
References parseFile().
Referenced by makeLoadButton().
VBox CellSocietyView.makeButtons () private
Definition at line 145 of file CellSocietyView.java.
References makeFFButton(), makeLoadButton(), makePauseButton(), makePlayButton(), makeSlowButton(), and makeStepButton().
Referenced by makeCAGame().
void CellSocietyView.makeCAGame (String gameName, int cellNum, String neighborhood, double prob, String gridType) private
Definition at line 117 of file CellSocietyView.java.
References CellularAutomata.getGrid(), Grid.init(), CellularAutomata.init(), makeButtons(), GridDrawer.makeGrid(), makeTimeline(), and GridDrawer.updateNextGen().
Referenced by parseFile().
Button CellSocietyView.makeFFButton () private
Definition at line 170 of file CellSocietyView.java.
References ACCELERATE_RATE, and makeUIButton().
Referenced by makeButtons().
Button CellSocietyView.makeLoadButton () private
Definition at line 141 of file CellSocietyView.java.
References loadNewFile(), and makeUIButton().
Referenced by CellSocietyView(), and makeButtons().
Button CellSocietyView.makePauseButton () private
Definition at line 177 of file CellSocietyView.java.
References makeUIButton().
Referenced by makeButtons().
Button CellSocietyView.makePlayButton () private
Definition at line 183 of file CellSocietyView.java.
References makeUIButton().
Referenced by makeButtons().
Button CellSocietyView.makeSlowButton () private
Definition at line 164 of file CellSocietyView.java.
References makeUIButton(), and SLOW_RATE.
Referenced by makeButtons().
Button CellSocietyView.makeStepButton () private
Definition at line 158 of file CellSocietyView.java.
References makeUIButton(), and updateView().
Referenced by makeButtons().
void CellSocietyView.makeTimeline (int time) private
Definition at line 133 of file CellSocietyView.java.
References updateView().
Referenced by makeCAGame().
Button CellSocietyView.makeUIButton (String name, EventHandler< MouseEvent > e) private
Definition at line 189 of file CellSocietyView.java.
Referenced by makeFFButton(), makeLoadButton(), makePauseButton(), makePlayButton(), makeSlowButton(), and makeStepButton().
void CellSocietyView.parseFile (File file) private
Definition at line 108 of file CellSocietyView.java.
References makeCAGame().
Referenced by loadNewFile().
void CellSocietyView.setUp () private
Definition at line 58 of file CellSocietyView.java.
References setUpGameTypes(), setUpGridTypes(), and setUpNbhoodTypes().
Referenced by CellSocietyView().
void CellSocietyView.setUpGameTypes () private
Definition at line 64 of file CellSocietyView.java.
References addGameType().
Referenced by setUp().
void CellSocietyView.setUpGridTypes () private
Definition at line 76 of file CellSocietyView.java.
Referenced by setUp().
void CellSocietyView.setUpNbhoodTypes () private
Definition at line 82 of file CellSocietyView.java.
Referenced by setUp().
void CellSocietyView.updateView () private
Definition at line 128 of file CellSocietyView.java.
References CellularAutomata.updateNextGen(), and GridDrawer.updateNextGen().
Referenced by makeStepButton(), and makeTimeline().
Member Data Documentation
final double CellSocietyView.ACCELERATE_RATE = 1.25 static private
Definition at line 26 of file CellSocietyView.java.
Referenced by makeFFButton().
final String CellSocietyView.DEFAULT_RESOURCE_PACKAGE = "resources/" static private
Definition at line 31 of file CellSocietyView.java.
final int CellSocietyView.FRAME_RATE = 2000 static private
Definition at line 32 of file CellSocietyView.java.
HashMap<String, CellularAutomata> CellSocietyView.gameTypes private
Definition at line 42 of file CellSocietyView.java.
HashMap<String, Grid> CellSocietyView.gridTypes private
Definition at line 43 of file CellSocietyView.java.
final int [][] CellSocietyView.MOORE_NEIGHBORHOOD = new int[][] {{-1, 0}, {1, 0}, {0, 1}, {0, -1}, {-1, -1}, {-1, 1}, {1, -1}, {1, 1}} static private
Definition at line 29 of file CellSocietyView.java.
Timeline CellSocietyView.myAnimation private
Definition at line 36 of file CellSocietyView.java.
ResourceBundle CellSocietyView.myButtonNames private
Definition at line 40 of file CellSocietyView.java.
CellularAutomata CellSocietyView.myCA private
Definition at line 34 of file CellSocietyView.java.
GridDrawer CellSocietyView.myGridView private
Definition at line 35 of file CellSocietyView.java.
int CellSocietyView.myHeight private
Definition at line 39 of file CellSocietyView.java.
BorderPane CellSocietyView.myRoot private
Definition at line 41 of file CellSocietyView.java.
Scene CellSocietyView.myScene private
Definition at line 37 of file CellSocietyView.java.
Referenced by getScene().
int CellSocietyView.myWidth private
Definition at line 38 of file CellSocietyView.java.
HashMap<String, int[][]> CellSocietyView.nbhoodTypes private
Definition at line 44 of file CellSocietyView.java.
final int [][] CellSocietyView.NEAR_NEIGHBORHOOD = new int[][] {{-1, 0}, {1, 0}, {0, 1}, {0, -1}} static private
Definition at line 28 of file CellSocietyView.java.
final double CellSocietyView.SLOW_RATE = .8 static private
Definition at line 27 of file CellSocietyView.java.
Referenced by makeSlowButton().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/CellSocietyView.java