cellsociety_team19: XMLReader Class Reference
XMLReader Class Reference
Public Member Functions
XMLReader ()
void chooseFile ()
void parseXML (File f)
CellularAutomata makeCA ()
Private Member Functions
Grid makeGrid ()
Map< String, Integer > makeParam ()
String getTextValue (Element ele, String tagName)
void setUpTypes ()
void setUpGameTypes ()
void addGameType (CellularAutomata ca)
void setUpGridTypes ()
void setUpNbhoodTypes ()
Private Attributes
Element docEle
HashMap< String, CellularAutomata > gameTypes
HashMap< String, Grid > gridTypes
HashMap< String, int[][]> nbhoodTypes
Static Private Attributes
static final int[][] NEAR_NEIGHBORHOOD
static final int[][] MOORE_NEIGHBORHOOD
Detailed Description
Definition at line 12 of file XMLReader.java.
Constructor & Destructor Documentation
XMLReader.XMLReader ()
Definition at line 27 of file XMLReader.java.
References setUpTypes().
Member Function Documentation
void XMLReader.addGameType (CellularAutomata ca) private
Definition at line 128 of file XMLReader.java.
References CellularAutomata.getName().
Referenced by setUpGameTypes().
void XMLReader.chooseFile ()
Definition at line 31 of file XMLReader.java.
References parseXML().
Referenced by CellSocietyView.loadNewFile().
String XMLReader.getTextValue (Element ele, String tagName) private
Definition at line 103 of file XMLReader.java.
Referenced by makeCA(), makeGrid(), and makeParam().
CellularAutomata XMLReader.makeCA ()
Definition at line 87 of file XMLReader.java.
References getTextValue(), makeGrid(), and makeParam().
Referenced by CellSocietyView.makeCAGame().
Grid XMLReader.makeGrid () private
Definition at line 62 of file XMLReader.java.
References getTextValue().
Referenced by makeCA().
Map<String, Integer> XMLReader.makeParam () private
Definition at line 73 of file XMLReader.java.
References getTextValue().
Referenced by makeCA().
void XMLReader.parseXML (File f)
Definition at line 45 of file XMLReader.java.
Referenced by chooseFile().
void XMLReader.setUpGameTypes () private
Definition at line 120 of file XMLReader.java.
References addGameType().
Referenced by setUpTypes().
void XMLReader.setUpGridTypes () private
Definition at line 132 of file XMLReader.java.
Referenced by setUpTypes().
void XMLReader.setUpNbhoodTypes () private
Definition at line 138 of file XMLReader.java.
Referenced by setUpTypes().
void XMLReader.setUpTypes () private
Definition at line 114 of file XMLReader.java.
References setUpGameTypes(), setUpGridTypes(), and setUpNbhoodTypes().
Referenced by XMLReader().
Member Data Documentation
Element XMLReader.docEle private
Definition at line 22 of file XMLReader.java.
HashMap<String, CellularAutomata> XMLReader.gameTypes private
Definition at line 23 of file XMLReader.java.
HashMap<String, Grid> XMLReader.gridTypes private
Definition at line 24 of file XMLReader.java.
final int [][] XMLReader.MOORE_NEIGHBORHOOD static private
Initial value:
= new int[][] { { -1, 0 },
            { 1, 0 }, { 0, 1 }, { 0, -1 }, { -1, -1 }, { -1, 1 }, { 1, -1 },
            { 1, 1 } }
Definition at line 18 of file XMLReader.java.
HashMap<String, int[][]> XMLReader.nbhoodTypes private
Definition at line 25 of file XMLReader.java.
final int [][] XMLReader.NEAR_NEIGHBORHOOD static private
Initial value:
= new int[][] { { -1, 0 },
            { 1, 0 }, { 0, 1 }, { 0, -1 } }
Definition at line 15 of file XMLReader.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/XMLReader.java