cellsociety_team19: Grid Class Reference
Grid Class Reference
Public Member Functions
Grid ()
Grid init (int size, int[][] neighborhood)
Cell getCellAt (int x, int y)
ArrayList< Cell > getNeighbors (Cell c)
ArrayList< Cell > findNeighbors (Cell cell, Paint paint)
int getTorusPoint (int x)
Cell[][] getCells ()
int getGridSize ()
Private Member Functions
void makeGrid ()
boolean checkBounds (int x, int y)
Private Attributes
int myGridSize
Cell[][] myCells
int[][] myNeighborhood
Detailed Description
Holds all cells in 2D array Keeps track of neighbors for given cell
Definition at line 10 of file Grid.java.
Constructor & Destructor Documentation
Grid.Grid ()
Definition at line 15 of file Grid.java.
Member Function Documentation
boolean Grid.checkBounds (int x, int y) private
Definition at line 37 of file Grid.java.
Referenced by getNeighbors().
ArrayList<Cell> Grid.findNeighbors (Cell cell, Paint paint)
Definition at line 55 of file Grid.java.
References getNeighbors().
Referenced by Fire.checkNextToFire(), GameOfLife.checkRules(), Segregation.getSamePercent(), Wator.ruleOne(), and Wator.ruleTwo().
Cell Grid.getCellAt (int x, int y)
Definition at line 33 of file Grid.java.
Referenced by Fire.setUpInitialConfig(), CellularAutomata.setUpInitialConfig(), and GridDrawer.updateNextGen().
Cell [][] Grid.getCells ()
Definition at line 70 of file Grid.java.
References myCells.
Referenced by Fire.setUpInitialConfig().
int Grid.getGridSize ()
Definition at line 74 of file Grid.java.
References myGridSize.
Referenced by TorusGrid.getTorusPoint(), and GridDrawer.GridDrawer().
ArrayList<Cell> Grid.getNeighbors (Cell c)
Definition at line 41 of file Grid.java.
References checkBounds(), Cell.getPosX(), Cell.getPosY(), and getTorusPoint().
Referenced by findNeighbors().
int Grid.getTorusPoint (int x)
Definition at line 66 of file Grid.java.
Referenced by getNeighbors().
Grid Grid.init (int size, int neighborhood[][])
Definition at line 17 of file Grid.java.
References makeGrid(), and myGridSize.
void Grid.makeGrid () private
Definition at line 25 of file Grid.java.
References myGridSize.
Referenced by init().
Member Data Documentation
Cell [][] Grid.myCells private
Definition at line 12 of file Grid.java.
Referenced by getCells().
int Grid.myGridSize private
Definition at line 11 of file Grid.java.
Referenced by getGridSize(), init(), and makeGrid().
int [][] Grid.myNeighborhood private
Definition at line 13 of file Grid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/Grid.java