cellsociety_team19: GridDrawer Class Reference
GridDrawer Class Reference
Public Member Functions
GridDrawer (Grid grid, String shape)
Group makeGrid (int width, int height)
void updateNextGen ()
Private Member Functions
void makeUnitGrid ()
double calculateCellWidth (int width)
double calculateCellHeight (int height)
void scale (double cellWidth, double cellHeight)
void scale (Shape s, double cellWidth, double cellHeight)
Shape drawUnitCell (int x, int y)
Shape drawTriangle (int x, int y)
Shape drawSquare (int x, int y)
Shape drawHexagon (int x, int y)
Private Attributes
Grid myGrid
String myShape
Shape[][] myShapes
Group myRoot
int gridSize
Detailed Description
Creates visual representation of grid for simulation
Definition at line 9 of file GridDrawer.java.
Constructor & Destructor Documentation
GridDrawer.GridDrawer (Grid grid, String shape)
Definition at line 16 of file GridDrawer.java.
References Grid.getGridSize(), and gridSize.
Member Function Documentation
double GridDrawer.calculateCellHeight (int height) private
Definition at line 55 of file GridDrawer.java.
Referenced by makeGrid().
double GridDrawer.calculateCellWidth (int width) private
Definition at line 51 of file GridDrawer.java.
Referenced by makeGrid().
Shape GridDrawer.drawHexagon (int x, int y) private
Definition at line 104 of file GridDrawer.java.
Referenced by drawUnitCell().
Shape GridDrawer.drawSquare (int x, int y) private
Definition at line 96 of file GridDrawer.java.
Referenced by drawUnitCell().
Shape GridDrawer.drawTriangle (int x, int y) private
Definition at line 87 of file GridDrawer.java.
Referenced by drawUnitCell().
Shape GridDrawer.drawUnitCell (int x, int y) private
Definition at line 74 of file GridDrawer.java.
References drawHexagon(), drawSquare(), and drawTriangle().
Referenced by makeUnitGrid().
Group GridDrawer.makeGrid (int width, int height)
Definition at line 33 of file GridDrawer.java.
References calculateCellHeight(), calculateCellWidth(), makeUnitGrid(), myRoot, and scale().
Referenced by CellSocietyView.makeCAGame().
void GridDrawer.makeUnitGrid () private
Definition at line 24 of file GridDrawer.java.
References drawUnitCell(), and gridSize.
Referenced by makeGrid().
void GridDrawer.scale (double cellWidth, double cellHeight) private
Definition at line 59 of file GridDrawer.java.
Referenced by makeGrid().
void GridDrawer.scale (Shape s, double cellWidth, double cellHeight) private
Definition at line 67 of file GridDrawer.java.
void GridDrawer.updateNextGen ()
Definition at line 42 of file GridDrawer.java.
References Grid.getCellAt(), Cell.getState(), and gridSize.
Referenced by CellSocietyView.makeCAGame(), and CellSocietyView.updateView().
Member Data Documentation
int GridDrawer.gridSize private
Definition at line 14 of file GridDrawer.java.
Referenced by GridDrawer(), makeUnitGrid(), and updateNextGen().
Grid GridDrawer.myGrid private
Definition at line 10 of file GridDrawer.java.
Group GridDrawer.myRoot private
Definition at line 13 of file GridDrawer.java.
Referenced by makeGrid().
String GridDrawer.myShape private
Definition at line 11 of file GridDrawer.java.
Shape [][] GridDrawer.myShapes private
Definition at line 12 of file GridDrawer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/GridDrawer.java