cellsociety_team19: Segregation Class Reference
Segregation Class Reference
Public Member Functions
Segregation ()
void setUpInitialConfig ()
void setUpInitialConfig (double probA, double probB)
void checkRules (Mover mover)
void move (Mover mover, ArrayList< Cell > possibleMoves)
Public Member Functions inherited from MoveCellularAutomata
MoveCellularAutomata (String name)
void setEmptyColor (Paint paint)
void addMover (Mover mover)
void removeMover (Mover mover)
void move (Mover mover, ArrayList< Cell > possibleMoves)
abstract void checkRules (Mover mover)
void checkRules ()
void updateNextGen ()
Public Member Functions inherited from CellularAutomata
CellularAutomata (String name)
CellularAutomata init (Grid grid, double prob)
abstract void setUpInitialConfig ()
void setUpInitialConfig (double probA, double probB)
void rule (Cell cell, Predicate< Cell > tester, Consumer< Cell > change)
void updateNextGen ()
void checkRules (Cell cell)
void checkRules ()
void handleUpdate ()
double getRandomDouble ()
Grid getGrid ()
String getName ()
double getProb ()
Private Member Functions
void ruleOne (Mover mover)
double getSamePercent (Cell cell)
Private Attributes
double percentColorTwo = 0.25
double percentColorOne = 0.25
ArrayList< Cell > emptyCells
Color color1 = Color.RED
Color color2 = Color.BLUE
Color empty = Color.WHITE
Detailed Description
Creates rules for Segregation simulation
Definition at line 9 of file Segregation.java.
Constructor & Destructor Documentation
Segregation.Segregation ()
Definition at line 18 of file Segregation.java.
References MoveCellularAutomata.setEmptyColor().
Member Function Documentation
void Segregation.checkRules (Mover mover)
Definition at line 46 of file Segregation.java.
References ruleOne().
double Segregation.getSamePercent (Cell cell) private
Definition at line 70 of file Segregation.java.
References Grid.findNeighbors(), CellularAutomata.getGrid(), and Cell.getState().
Referenced by ruleOne().
void Segregation.move (Mover mover, ArrayList< Cell > possibleMoves)
Definition at line 63 of file Segregation.java.
References Mover.getCell().
Referenced by ruleOne().
void Segregation.ruleOne (Mover mover) private
Definition at line 50 of file Segregation.java.
References Mover.getCell(), CellularAutomata.getProb(), getSamePercent(), Mover.isState(), and move().
Referenced by checkRules().
void Segregation.setUpInitialConfig ()
Definition at line 24 of file Segregation.java.
void Segregation.setUpInitialConfig (double probA, double probB)
Definition at line 28 of file Segregation.java.
References MoveCellularAutomata.addMover(), CellularAutomata.getGrid(), and CellularAutomata.getRandomDouble().
Member Data Documentation
Color Segregation.color1 = Color.RED private
Definition at line 14 of file Segregation.java.
Color Segregation.color2 = Color.BLUE private
Definition at line 15 of file Segregation.java.
Color Segregation.empty = Color.WHITE private
Definition at line 16 of file Segregation.java.
ArrayList<Cell> Segregation.emptyCells private
Definition at line 13 of file Segregation.java.
double Segregation.percentColorOne = 0.25 private
Definition at line 12 of file Segregation.java.
double Segregation.percentColorTwo = 0.25 private
Definition at line 11 of file Segregation.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team19/repository/src/Segregation.java